-- Atualizar posts com URLs de imagens que funcionem
UPDATE posts SET media_url = 'https://picsum.photos/400/600?random=1' WHERE profile_id = (SELECT id FROM profiles WHERE username = 'bella_model') AND media_url LIKE '%placeholder%' LIMIT 1;
UPDATE posts SET media_url = 'https://picsum.photos/400/600?random=2' WHERE profile_id = (SELECT id FROM profiles WHERE username = 'bella_model') AND media_url LIKE '%placeholder%' AND media_url != 'https://picsum.photos/400/600?random=1' LIMIT 1;
UPDATE posts SET media_url = 'https://picsum.photos/400/600?random=3' WHERE profile_id = (SELECT id FROM profiles WHERE username = 'bella_model') AND media_url LIKE '%placeholder%' AND media_url NOT IN ('https://picsum.photos/400/600?random=1', 'https://picsum.photos/400/600?random=2') LIMIT 1;
UPDATE posts SET media_url = 'https://picsum.photos/400/600?random=4' WHERE profile_id = (SELECT id FROM profiles WHERE username = 'bella_model') AND media_url LIKE '%placeholder%' AND media_url NOT IN ('https://picsum.photos/400/600?random=1', 'https://picsum.photos/400/600?random=2', 'https://picsum.photos/400/600?random=3') LIMIT 1;
UPDATE posts SET media_url = 'https://picsum.photos/400/600?random=5' WHERE profile_id = (SELECT id FROM profiles WHERE username = 'bella_model') AND media_url LIKE '%placeholder%' AND media_url NOT IN ('https://picsum.photos/400/600?random=1', 'https://picsum.photos/400/600?random=2', 'https://picsum.photos/400/600?random=3', 'https://picsum.photos/400/600?random=4') LIMIT 1;

-- Atualizar posts do badmi também
UPDATE posts SET media_url = 'https://picsum.photos/400/600?random=6' WHERE profile_id = (SELECT id FROM profiles WHERE username = 'badmi') AND media_url LIKE '%placeholder%' LIMIT 1;
UPDATE posts SET media_url = 'https://picsum.photos/400/600?random=7' WHERE profile_id = (SELECT id FROM profiles WHERE username = 'badmi') AND media_url LIKE '%placeholder%' AND media_url != 'https://picsum.photos/400/600?random=6' LIMIT 1;
UPDATE posts SET media_url = 'https://picsum.photos/400/600?random=8' WHERE profile_id = (SELECT id FROM profiles WHERE username = 'badmi') AND media_url LIKE '%placeholder%' AND media_url NOT IN ('https://picsum.photos/400/600?random=6', 'https://picsum.photos/400/600?random=7') LIMIT 1;
UPDATE posts SET media_url = 'https://picsum.photos/400/600?random=9' WHERE profile_id = (SELECT id FROM profiles WHERE username = 'badmi') AND media_url LIKE '%placeholder%' AND media_url NOT IN ('https://picsum.photos/400/600?random=6', 'https://picsum.photos/400/600?random=7', 'https://picsum.photos/400/600?random=8') LIMIT 1;
UPDATE posts SET media_url = 'https://picsum.photos/400/600?random=10' WHERE profile_id = (SELECT id FROM profiles WHERE username = 'badmi') AND media_url LIKE '%placeholder%' AND media_url NOT IN ('https://picsum.photos/400/600?random=6', 'https://picsum.photos/400/600?random=7', 'https://picsum.photos/400/600?random=8', 'https://picsum.photos/400/600?random=9') LIMIT 1;
